# Soil property maps

*R. Baritz*

## Definitions and objectives

\index{Soil property maps|textbf|(}
Soil property maps represent spatial information about soil properties to a certain depth or for soil horizons\index{Soil horizons}. Conventionally, soil property maps are generated as polygon maps, with properties from typical soil profiles representing soil mapping units.
Digital Soil Mapping (DSM)\index{Digital Soil Mapping (DSM)} allows more accurate spatial mapping of soil properties, including the spatial quantification of the prediction error\index{Prediction!error}. The quality of such predictions improves with increasing number of local observations (e.g. soil profiles) available to build the prediction model\index{Prediction!model}. Whenever possible, DSM is recommended. 

The development of soil property maps via DSM is spatially flexible. For different soil properties (e.g. concentration and stocks of nutrients in the soil, carbon, heavy metals, pH, cation exchange capacity, physical soil properties such as particle sizes and bulk density, etc.), various depth classes and spatial resolution can be modeled depending on project and mapping objectives and available input data. For GSOCmap\index{Global Soil Organic Carbon Map (GSOCMap)}, a 1 km grid is pursued. The same methodology and input data can also be used to produce higher resolution soil grids.

The mapping of global soil organic carbon (GSOC) stocks will be the first implementation of a series of other soil property grids to be developed for GLOSIS\index{Soil Information System (SIS)!global}, based on the typical GSP country-driven system. GSOCmap will demonstrate the capacity of countries all around the globe to compile and manage national soil information systems and to utilize and evaluate these data following agreed international specifications. The GSP Secretariat, FAO, and its regional offices, as well as the Regional Soil Partnerships, are challenged together with the GSP members, especially the members of INSII, to establish national capacity and soil data infrastructures to enable soil property mapping.
\index{Soil property maps|textbf|)}

## Generic mapping of soil grids: upscaling of plot-Level measurements and estimates

The following table presents an overview of different geographic upscaling approaches, recommended to produce soil property maps, in particular, GSOCmap.

|   |   |                                                                       | 
|-------------------|-------------------------|-----------------------------------------|
| Conventional upscaling [@lettens2004soil]  |  Class-matching | Derive average SOC stocks per class: soil type for which a national map exists, or combination with other spatial covariates (e.g. land use category, climate type, biome, etc.). This approach is used in the absence of spatial coordinates of the source data.  |
|                         | Geomatching     | Point locations with spatial referencing are overlaid with geographic information system (GIS) layers of important covariates (e.g. a soil map). Upscaling is based on averaged SOC values per mapping unit.  | 
|  Digital soil mapping [@dobos2006digital] \index{Digital Soil Mapping (DSM)}    | Data mining and geostatistics  | Multiple regression, classification tree, random forests, regression-kriging, kriging with external drift.  | 


Digital soil mapping is based on the development of functions for upscaling point data (with soil measurements) to a full spatial extent using correlated environmental covariates, for which spatial data are available.

> **DSM**: Concept of environmental correlation that explores the quantitative relationship between environmental variables and soil properties and could be used to predict the latter with multivariate prediction techniques.

The approaches outlined and demonstrated in this technical manual consider the reference framework of the SCORPAN
model for digital soil mapping (DSM; @mcbratney2003digital). In the
SCORPAN reference framework a soil attribute (e.g., SOC) can be
predicted as a function of the soil forming environment, in
correspondence with soil forming factors from the Dokuchaev hypothesis
and Jenny's soil forming equation based on climate, organisms, relief,
parent material and elapsed time of soil formation
\citep{Florinsky2012}. The SCORPAN (Soils, Climate,
Organisms, Parent material, Age and (N) space or spatial position, see
\cite{mcbratney2003digital}) reference framework is a empirical approach
that can be expressed as in Eq. (1):

\begin{equation}
Sa_{[x; y ~ t]}
=f(S_{[x; y ~ t]},C_{[x; y ~ t]},O_{[x; y ~ t]},R_{[x; y ~ t]},P_{[x;
y ~ t]},A_{[x; y ~ t]})
\end{equation}

where $Sa$ is the soil attribute of interest at a specific location
\textcolor{red}{N (represented by the spatial coordinates of field
observations $x$; $y$) and representative for a specific time frame
($t$)}; $S$ is the soil or other soil properties  that
are correlated with $Sa$; $C$ is the climate or climatic properties
of the environment; $O$ are the organisms, vegetation, fauna or human
activity; $R$ is topography or landscape attributes; $P$ is parent
material or lithology; and $A$ is the substrate age or the time
factor. To generate predictions of $Sa$ across places
where no soil data is available, $N$ should be explicit for the
information layers representing the soil forming factors. These
predictions will be representative of the time period ($t$) when soil
available data was collected. Therefore, the prediction factors
ideally should represent, the conditions of the soil forming
environment for the same period of time (as much as possible) when
soil available data was collected. In Eq. (1) the left side is
usually represented by the available geo-spatial soil observational
data (e.g., from legacy soil profile collections) and the right side
of the equation is represented by the soil prediction factors. These
prediction factors are normally derived from four main sources of
information: a) thematic maps (i.e., soil type, rock type, land use
type); b) remote sensing (i.e., active and passive); c) climate
surfaces and meteorological data; and d) digital terrain analysis or
geomorphometry. The SCORPAN reference framework is widely used, but
one critical challenge is to quantify the relative importance of the
soil forming factors (i.e., prediction factors) that could explain the
underlying soil processes controlling the spatial variability of a
specific soil attribute (i.e., SOC).
