# Deliverables {#deliverables}
*Y. Yigini*

In 2016, the the need of the development of a tool to assess global SOC stocks was identified by the GSP Plenary Assembly. As a contribution to the Sustainable Development Goal indicator 15.3.1 which aims at estimating the total degraded land area, the preparatory work to develop a GSOCmap was completed by the end of 2016.

During 2017, the first ever GSOCmap was realized using a country driven bottom-up approach. The soil data from contributing countries were collected by the GSP Secretariat. The [*GSP Soil Data Policy*](http://www.fao.org/3/a-bs975e.pdf) [see @gsp_data_2017, Chapter 8.5], ensured that the national terms of condition are fully respected during the whole process of data sharing. National soil data was compiled and harmonized with regard to differences in laboratory methodologies and sampling units. Furthermore, a global soil database was created using recovered soil data legacy from archives, institutions and projects. Finally, a global data harmonization was conducted by the GSP Secretariat including quality control, mosaicking, border harmoization and gap filling.

The GSOCmap V1.0 has been launched on the 5^th^ of December 2017 during World Soil Day. At the launching, the map is based on more than 1 million sampling points. The product is hosted by GLOSIS and constantly updated. It is available as an online application, accessible at the link: http://www.fao.org/global-soil-partnership/pillars-action/4-information-and-data/global-soil-organic-carbon-gsoc-map/en/.

The following **deliverables** are comprised with GSOCmap V1.0:

*   GSOCmap V1.0 is digitally delivered in grid (GeoTIFF) format with a 30 arc-second resolution. The global data can be downloaded as `GSOCmap.tif`.
*   The associated uncertainty layers and prediction quality figures, including qualitative assessment from conventional upscaling, and quantitative assessment from DSM methods. The prediction uncertainty is provided with the estimated map quality measures such as mean error, mean absolute error, (root) mean squared error. 
*   The metadata providing standardized information about a data set, for example, the maintaining institution through which the data can be accessed. In the case of the GSOCmap, a project-specific metadata template has been prepared. It deviates from the metadata elements listed in common standards such as ISO 19115. The template is following the [*GSP Guidelines for Sharing National Data/Information to Compile a Global Soil Organic Carbon (GSOC) Map*](http://www.fao.org/3/a-bp164e.pdf) [@gsp_guidelines_2017] which provide technical guidelines to prepare and evaluate spatial soil data sets. Soil-specific methodical elements are considered including metadata describing the data sources used for SOC mapping and the upscaling method.
* A GSOCmap information leaflet is provided in three different languages, giving an overview of the objectives and the development process. Summarized quantitative results obtained from GSOCmap V1.0 are given, e.g. estimated SOC stocks for different soil types, land covers or climate zones.
* This cookbook on SOC mapping was built using the Github development environment. An updated online version of the cookbook which will include improvements from the continuous work process of the GSOCmap project is provided for users on the [GSP official website](http://www.fao.org/global-soil-partnership/pillars-action/4-information-and-data/global-soil-organic-carbon-gsoc-map/en/).

The GSOCmap provides users and relevant stakeholders such as policy makers with useful information to monitor soil condition, identify degraded land and soil areas, set restoration targets, explore SOC sequestration potentials, support the greenhouse gas emission reporting under the United Nations Framework Convention on Climate Change (UNFCCC) and make evidence based decisions to mitigate and adapt to a changing climate on a national and global level.

In the future, the GSP aims to adopt feasible guidelines for measuring, mapping, monitoring and reporting SOC stocks locally. This objective well as the continuing capacity development process through the global SOC mapping programme and DSM training on national level are the basis for integrating new and updated national SOC maps to produce GSOCmap V2.0. as a step towards establishing a global SOC monitoring system.
